version: 1.0.0.{build}

image: Visual Studio 2019

configuration: Release

environment:
  global:
    TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: stable
    CRATE_NAME: dexiosgui
    CARGO_HOME: "c:\\cargo"
    RUSTUP_HOME: "c:\\rustup"


install:
    - set QTDIR=C:\Qt\6.3.0
    - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\6.3.0\msvc2019_64\bin
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-host %TARGET%
    - set PATH=%PATH%;C:\cargo\bin
    - rustc -Vv
    - cargo -V

build_script:
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    # - cargo test
    - cargo build --release
    - dir
    - cd qtgui
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    - dir
    - nmake
    - cd %APPVEYOR_BUILD_FOLDER%
    - dir
    - mkdir dexiosgui_win_x64
    - cd dexiosgui_win_x64
    - xcopy %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\dexiosgui_win_x64\
    - xcopy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\dexiosgui_win_x64\
    - xcopy %APPVEYOR_BUILD_FOLDER%\qtgui\build\dexiosgui.exe %APPVEYOR_BUILD_FOLDER%\dexiosgui_win_x64\
    - windeployqt --release --no-translations --no-opengl-sw dexiosgui.exe
    
artifacts:
    - path: dexiosgui_win_x64
      type: zip

# deploy tagged releases to Github releases
deploy:
      - provider: GitHub
        release: $(appveyor_repo_tag_name)
        description: 'Release of dexiosgui v${appveyor_repo_tag_name}'
        draft: false
        prerelease: false
        do_rel: true
        auth_token:
          secure: +tfhnWlsWPfHXUdLqWA8LjT0q9toLiCuBZBUs+tRXLKTYOaxNpwZ/ezF25o8uvv+
        artifact: dexiosgui_win_x64.zip
        force_update: true
        on:
          branch: master                # release from master branch only
          appveyor_repo_tag: true      # deploy on tag push only

