[package]
name = "adapter"
version = "4.0.0"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[lib]
name = "adapter"
crate-type = ["staticlib"]

[dependencies]
dexios-core = { path = "../dexios-core" }
interface = { path = "../interface" }
zeroize = "1.3.0"
